apiVersion: v1
kind: Template
metadata:
  name: rhsm-conduit

parameters:
  - name: NAMESPACE
    description: Name of your project (e.g. myproject)
  - name: SOURCE_REPOSITORY_URL
    description: The URL of the repository with your application source code.
    displayName: Git repository URI
    value: https://github.com/RedHatInsights/rhsm-conduit.git
    required: true
  - name: SOURCE_REPOSITORY_REF
    description: The source repository reference that is to be used when building
    value: master
    required: true
  - name: IMAGE_TAG
    description: The image tag to apply to the build
    value: latest
    required: true
  - name: MEMORY_ALLOCATION
    description: How much memory should be allocated (i.e 1Gi)
    displayName: Memory Allocation
    value: 1Gi
    required: true
  - name: CPU_ALLOCATION
    description: How many CPUs should be allocated
    displayName: CPU Allocation
    value: "1"
    required: true

objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    labels:
      app: rhsm-conduit
    name: rhsm-conduit
    namespace: "${NAMESPACE}"

- kind: BuildConfig
  apiVersion: v1
  metadata:
    labels:
      app: rhsm-conduit
    name: rhsm-conduit
    namespace: "${NAMESPACE}"
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: rhsm-conduit:${IMAGE_TAG}
    source:
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: DockerImage
          name: docker.io/fabric8/s2i-java
      type: Source
    triggers:
      - type: ConfigChange
      - type: GitHub
        github:
          secretReference:
            name: rhsm-conduit-github-webhook
    resources:
      limits:
        memory: ${MEMORY_ALLOCATION}
        cpu: ${CPU_ALLOCATION}

{% if parameters.get('NAMESPACE') == 'buildfactory' %}
- kind: BuildConfig
  apiVersion: v1
  metadata:
    labels:
      app: rhsm-conduit
    name: rhsm-conduit-stable
    namespace: "${NAMESPACE}"
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: rhsm-conduit:stable
    source:
      git:
        ref: release/production
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: DockerImage
          name: docker.io/fabric8/s2i-java
      type: Source
    triggers:
      - type: ConfigChange
      - type: GitHub
        github:
          secretReference:
            name: rhsm-conduit-github-webhook
    resources:
      limits:
        memory: ${MEMORY_ALLOCATION}
        cpu: ${CPU_ALLOCATION}
{% endif %}
